version: '3.7'

services:
  mysql:
    image: 'mysql/mysql-server:8.0.21-1.1.17'
    container_name: 'mysql'
    expose:
      - '3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_DATABASE=db_security'
      - 'MYSQL_ROOT_HOST=%'
      - 'MYSQL_ROOT_USER=root'

  myapp:
    depends_on:
      mysql:
        condition: service_started
    build: ./
    container_name: 'java-app'
    links:
      - 'mysql'
    ports:
      - '8080:8080'