version: '3'

services:
  mysql:
    image: 'mysql/mysql-server:latest'
    container_name: 'mysql'
    ports:
      - 33080:33080
    environment:
      - 'MYSQL_USER=root'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=12345'
      - 'MYSQL_DATABASE=db_security'

  myapp:
    build: ./
    container_name: java-app
    ports:
      - 8080:8080